[package]
name = "zeusircd2"
authors = ["Moebius ( Pryan )"]
license = "LGPL-2.1-or-later"
version = "0.0.1"
edition = "2018"
rust-version = "1.57"
description = "Next generation ircd"
repository = "https://github.com/Pryancito/zeusircd2"
categories = ["network-programming"]
keywords = ["irc"]

[dependencies]
tokio = { version = "1.0", features = [ "full" ] }
tokio-util = { version = "0.7.0", features = [ "codec" ] }
tokio-stream = "0.1"
tokio-postgres = { version = "0.7", optional = true }
tracing = "0.1"
futures = "0.3.0"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.0"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.0", features = ["derive"] }
validator = { version = "0.14", features = [ "derive" ] }
bytes = "1.1.0"
const-table = "0.1.0"
flagset = "0.4"
argon2 = "0.4"
rpassword = "6.0"
tokio-rustls = { version = "0.23", optional = true }
rustls = { version = "0.20", optional = true }
rustls-pemfile = { version = "1.0", optional = true }
tokio-openssl = { version = "0.6", optional = true }
openssl = { version = "0.10", optional = true }
lazy_static = "1.4"
trust-dns-resolver = { version = "0.21", optional = true }
sqlite = { version = "0.37.0", optional = true }
async-trait = "0.1.73"
mysql_async = { version = "0.35.1", optional = true }
tokio-tungstenite = "0.20"
tungstenite = "0.20"
url = "2.4"
lapin = "2.3"
amq-protocol = "7.1"
amq-protocol-types = "7.1"
serde_json = "1.0"
anyhow = "1.0"

[features]
default = []
# prefer rustls for almost systems
tls_rustls = [ "rustls", "tokio-rustls", "rustls-pemfile" ]
# use openssl if rustls with ring doesn't work - for example old non-SSE2 machines
tls_openssl = [ "openssl", "tokio-openssl" ]
dns_lookup = [ "trust-dns-resolver" ]
sqlite3 = ["sqlite"]
mysql = ["mysql_async"]

[dependencies.tracing-subscriber]
version = "0.3.1"
default-features = false
features = ["fmt", "ansi", "env-filter", "tracing-log"]

[dev-dependencies]
tokio = { version = "1.0", features = [ "full", "test-util" ] }
