[package]
name = "simple-irc-server"
authors = ["Mateusz Szpakowski"]
license = "GNU Lesser General Public License v2.1"
version = "0.1.0"
edition = "2018"
description = "Simple IRC server"
categories = ["network-programming"]
keywords = ["irc"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = [ "full" ] }
tokio-util = { version = "0.7.0", features = [ "codec" ] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.1", default-features = false,
            features = ["fmt", "ansi", "env-filter", "tracing-log"] }
futures = "0.3.0"
